# NumPy Array Analysis

The `array_2d.shape` returns the dimensions, `array_2d.dtype` shows the data type, and `array_2d.size` gives the total number of elements.

When we use `np.array([[1,2,3,4,5], [2,4,6,8,10]])`, we create an array with 2 rows and 5 columns.

So is 
2*5 matrix 

(1,2,3,4,5)
(2,4,6,8,10)

In [10]:
# 0D dimensioned arrays 
import numpy as np

print(np.array(42))
print(np.array(142))
print(np.array(15))

42
142
15


In [ ]:
# 2D arrays properties
import numpy as np

array_2d = np.array([[1,2,3,4,5], [2,4,6,8,10]])

print(array_2d.shape)
print(array_2d.dtype)
print(array_2d.size) 


(2, 5)
int64
10


In [10]:
import numpy as np
arr = np.array([0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])
print(arr.size)

16


In [2]:
import numpy as np 
# Create array with ones, zeros. 

arr = np.zeros(3)
arr2 = np.ones(4)

print(arr,arr2)

[0. 0. 0.] [1. 1. 1. 1.]


In [15]:
import numpy as np 
# Steps of increment when creating new array list

arr = np.arange(start = 4, stop = 10, step = 0.5)
arr2 = np.arange(16,-6,-2)
print(arr.tolist())
print(arr2.tolist())

[4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5]
[16, 14, 12, 10, 8, 6, 4, 2, 0, -2, -4]


In [ ]:
import numpy as np
# linespace
# arr = np.linspace(start = 2, end = 3, 5 is the number of val in between 2 and 3, where every step is equal
# linspace = values between 2, 3, 5 is the steps made
# N div

arr = np.linspace(2,3,5)
arr.tolist()


[2.0, 2.25, 2.5, 2.75, 3.0]

# 3D Matrix

`Example: (2,2,3) = (z,x,y)`

| Dimension | Name | Description | Our Example |
|-----------|------|-------------|-------------|
| z | Layers/Depth | Number of "sheets" stacked | 2 layers |
| x | Rows | Number of horizontal rows per layer | 2 rows |
| y | Columns | Number of vertical columns per row | 3 columns |

**Layer 0:**
```
[426,  2, 46]
[ 53, 42, 35]
```

**Layer 1:**
```
[646,  57, 309]
[ 89, 149, 100]
```

Index rules still apply: 0, 1, 2...


In [4]:
import numpy as np
arr = np.array([[[426, 2, 46], 
  [53, 42, 35]],

 [[646, 57, 309], 
  [89, 149, 100]]])

arr.shape

(2, 2, 3)

In [8]:
# Change numbers: 
import numpy as np
arr = np.array([0, 2, 3, 4, 5, 6, 7, 8])

# Print original array
print("Original array:", arr)

# Change value at indexes 2, 4, and 6
arr[2] = 13
arr[4] = 15
arr[6] = 17

# Print array with updated values
print("New array:", arr.tolist())
# .tolist() prevents extra spacing 

Original array: [0 2 3 4 5 6 7 8]
New array: [0, 2, 13, 4, 15, 6, 17, 8]


# Random Number Generation in NumPy

NumPy provides several functions to generate random numbers:

- **`rand()`**: Generates an array of random numbers from a uniform distribution over `[0, 1]`.  
    *Example:* `np.random.rand(3)` → `[0.12, 0.85, 0.44]`

- **`randn()`**: Generates an array of random numbers from a standard normal distribution (mean 0, variance 1).  
    *Example:* `np.random.randn(3)` → `[0.23, -1.12, 0.77]`

- **`randint()`**: Generates random integers from a specified range.  
    *Example:* `np.random.randint(1, 10, 3)` → `[3, 7, 1]`

- **`choice()`**: Generates a random sample from a given 1-D array.  
    *Example:* `np.random.choice([10, 20, 30], 2)` → `[20, 10]`

These functions are useful for simulations, initializing arrays, or sampling data.

In [28]:
import  numpy as np

arr = np.array([5, 10, 15, 20, 25, 30])

randomArr = np.random.choice(arr, size=2)
print('1D:', randomArr.tolist())

1D: [5, 25]


# NumPy Array Manipulation Functions

| Function | Description | Example |
|----------|-------------|---------|
| `np.append()` | Add elements to the end of an array | `np.append(arr, [7, 8])` |
| `np.insert()` | Insert elements at specific positions | `np.insert(arr, 2, 99)` |
| `np.delete()` | Remove elements by index | `np.delete(arr, [1, 3])` |

**Note:** All operations create new arrays and don't modify the original.

In [14]:
# Examples of Insert and Delete Operations
import numpy as np

# Create an initial numpy array
my_array = np.array([10, 20, 30, 40, 50])
print("Original array:", my_array)

# Delete element at index 2
new_array = np.delete(my_array, 2)
print("After deleting index 2:", new_array)

# Insert value 60 at index 3
new_array2 = np.insert(my_array, 3, 60)
print("After inserting 60 at index 3:", new_array2)

# Inserting Values at multiple indices
array = np.arange(1, 11)
array3 = np.insert(array, [3, 5], 50)
print("\nOriginal array 1-10:", array)
print("After inserting 50 at indices 3 and 5:", array3.tolist())

# 2D array operations
print("\n--- 2D Array Operations ---")
my_array_2d = np.array([[11, 22], [33, 44]])
print("Original 2D array:")
print(my_array_2d)

# Inserting row
new_array1 = np.insert(my_array_2d, 1, 55, axis=0)
print("\nAfter inserting 55 in the row position, with index 1:")
print(new_array1)

# Deleting row
del_array = np.delete(my_array_2d, 1, axis=0)
print("\nAfter deleting row at index 1:")
print(del_array)

Original array: [10 20 30 40 50]
After deleting index 2: [10 20 40 50]
After inserting 60 at index 3: [10 20 30 60 40 50]

Original array 1-10: [ 1  2  3  4  5  6  7  8  9 10]
After inserting 50 at indices 3 and 5: [1, 2, 3, 50, 4, 5, 50, 6, 7, 8, 9, 10]

--- 2D Array Operations ---
Original 2D array:
[[11 22]
 [33 44]]

After inserting 55 in the row position, with index 1:
[[11 22]
 [55 55]
 [33 44]]

After deleting row at index 1:
[[11 22]]


In [15]:
import numpy as np 
scores = np.array([[85, 90, 77, 46],
                  [92, 88, 66, 50],
                  [78, 85, 99, 76]])

new_scores = np.delete(scores,1, axis = 0)
print(new_scores)

[[85 90 77 46]
 [78 85 99 76]]


# Append 
## Adding Value at the last index

Difference between append and insert
1. `np.insert` to add an array, not just single values. 
2. `np.append` allows you to put it in a dimension, `np.insert` allows you to set the index
3. `np.append` is just the “always add to the end” convenience; insert lets you put a whole block anywhere.
4.  `np.append(array,value)`

In [ ]:
import numpy as np

T = np.arange(23)
V = np.append(T,66)

print(V.tolist())

## Stack
### Stacking Multiple arrays together
| Function | Description | Example |
|----------|-------------|---------|
| `np.stack()` | Combine array into a bigger array | `np.stack((arr1, arr2), axis = 0)` |

**Note:** np.split also works in the h,v,d version

In [1]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

hstack = np.hstack((array1, array2))
print("Horizontal stack: \n", hstack)

vstack = np.vstack((array1, array2))
print("Vertical stack: \n", vstack)

dstack = np.dstack((array1, array2))
print("Depth stack: \n",dstack)

Horizontal stack: 
 [1 2 3 4 5 6]
Vertical stack: 
 [[1 2 3]
 [4 5 6]]
Depth stack: 
 [[[1 4]
  [2 5]
  [3 6]]]


## Split
### Separating a NumPy array into multiple smaller arrays.

| Function | Description | Example |
|----------|-------------|---------|
| `np.split()` | Split array into equal-sized sub-arrays | `np.split(arr, 3)` |
| `np.array_split()` | Split array into sub-arrays (allows unequal sizes) | `np.array_split(arr, 4)` |

**Note:** np.split also works in the h, v, d version  
Example:  
`np.hsplit()` or `np.vsplit()` or `np.dsplit()`
| Function | Description |
|----------|-------------|
| `np.hsplit()` | Split array columnly, imagine slicing a cake vertically|
| `np.vsplit()` | Split array rowly, imagine slicing a cake horizontally|
| `np.dsplit()` | Split array with depth |

**Unequal split example:**  
`newArr2 = np.array_split(arr, [2, 5])`  
Split at index:  
`print('\nSplit the array at index 2 and 5\n', newArr2)`  

In [5]:
import numpy as np

array1 = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])
                  
array2 = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   [[7, 8, 9],
                    [10, 11, 12]],
                   [[13, 14, 15],
                    [16, 17, 18]]])                

hsplit = np.hsplit(array1, 3)
print("Horizontal split:")
print(hsplit)
print(hsplit[1])

vsplit = np.vsplit(array1, 3)
print("Vertical split:")
print(vsplit)
print(vsplit[1])

dsplit = np.dsplit(array2, 3)
print("Depth split:")
print(dsplit)
print(dsplit[1])

Horizontal split:
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
[[2]
 [5]
 [8]]
Vertical split:
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[[4 5 6]]
Depth split:
[array([[[ 1],
        [ 4]],

       [[ 7],
        [10]],

       [[13],
        [16]]]), array([[[ 2],
        [ 5]],

       [[ 8],
        [11]],

       [[14],
        [17]]]), array([[[ 3],
        [ 6]],

       [[ 9],
        [12]],

       [[15],
        [18]]])]
[[[ 2]
  [ 5]]

 [[ 8]
  [11]]

 [[14]
  [17]]]
