# Things to Add
1. Operations +-*/
2. Broadcasting operations
3. Scalar Operations
4. math function, np.sin, np.log, np.exp, np.sqrt. https://numpy.org/doc/stable/reference/routines.math.html
5. np.where is like if statement, eg: np.where(cond, 'then', 'else'), [] prints out values

In [6]:
# 1. Operations
# Example:
import numpy as np 

arr = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[4,6]])
arr3 = arr+arr2

arr4 = arr*arr2

print(arr3)
print(arr4)

[[ 2  4]
 [ 7 10]]
[[ 1  4]
 [12 24]]


In [ ]:
# 2. Broadcasting data: 
# One arr must be subset of the other
# Cannot calculate if different shape, size
import numpy as np 

arr = np.array([[1,2],[3,4]])
arr2 = np.array([1,2])
arr3 = arr+arr2
arr4 = arr*arr2

print(arr3)

[[2 4]
 [4 6]]


In [11]:
# 3. Scalar Operations
import numpy as np 

arr = np.array([[1,2],[3,4]])

print(3*arr)

[[ 3  6]
 [ 9 12]]


In [19]:
# 4. math function, np.sin, np.log, np.exp, np.sqrt

import numpy as np 
arr = np.radians(30)
was = np.sin(arr)
print(was)

0.49999999999999994


In [26]:
arr = np.array([1,2,3,4,5,-1,0.5,0.8])

statement = arr[np.where(arr > 0.5)]
print(statement.tolist())


[1.0, 2.0, 3.0, 4.0, 5.0, 0.8]
